id: A16534C9D
title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
type: translation
pechas:
- I9EAC5906
- ID62982B9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:29.591438
  last_modified_at: 2023-01-04 11:55:29.591452
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9EAC5906/D63D: FD41
  ID62982B9/5DB0: FD41
